#MODEL_PATH = "/var/tak/src/model/yolov2.h5" # set to None to always create from cfg/weights files
MODEL_PATH = "/tmp/yolov2.h5"
LIBRARY_PATH = "/var/task/src/lib"
ANCHORS_PATH = "/var/task/src/model/yolov2.anchors"
CLASSES_PATH = "/var/task/src/model/yolov2.classes"
CONFIG_PATH = "/var/task/src/model/yolov2.cfg"
WEIGHTS_PATH = "/var/task/src/model/yolov2.weights" 
MODEL_IMAGE_SIZE = (608, 608)
MIN_CONFIDENCE = 0.5
MAX_OVERLAP = 0.35
