MODEL_PATH = None # "/src/model/yolov2.h5" # set to None to always create from cfg/weights files
LIBRARY_PATH = "src/lib"
ANCHORS_PATH = "src/model/yolov2.anchors"
CLASSES_PATH = "src/model/yolov2.classes"
CONFIG_PATH = "src/model/yolov2.cfg"
WEIGHTS_PATH = "src/model/yolov2.weights" 
MODEL_IMAGE_SIZE = (608, 608)
MIN_CONFIDENCE = 0.5
MAX_OVERLAP = 0.35
